# .github/release.yml

changelog:
  exclude:
    labels:
      - pipeline
      - wontfix
  categories:
    - title: 🎁 New Content
      labels:
        - content
    - title: ✨ Enhancements
      labels:
        - enhancement
        - tutorial
    - title: 🪲🔨 Bug Fixes
      labels:
        - bug
